# Generated by Django 2.1.3 on 2018-12-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0002_auto_20181120_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
