# Generated by Django 2.1.3 on 2019-02-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0004_auto_20190201_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
