# Generated by Django 2.1.3 on 2019-02-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0007_auto_20190217_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
