# Generated by Django 2.1.3 on 2019-02-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0009_auto_20190217_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='width',
        ),
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
